Add missing #include <cstdint>
Summary:
Fixes this build error with gcc10:

```
In file included from ../poprithms/poprithms/src/poprithms/compute/host/gridpointhelper.cpp:5:
../poprithms/poprithms/src/poprithms/compute/host/include/gridpointhelper.hpp:18:16: error: 'uint64_t' does not name a type; did you mean 'u_int64_t'?
   18 |   using Row  = uint64_t;
      |                ^~~~~~~~
      |                u_int64_t
```

Ref T36072.

Reviewers: #poprithms, jamesn

Reviewed By: #poprithms, jamesn

Maniphest Tasks: T38786, T36072

Differential Revision: https://phabricator.sourcevertex.net/D45215